version: '3'

services:
  dsider:
    build: .
    image: 958527256docker/dsider:latest
    container_name: dsider
    restart: always
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
    volumes:
      - ./logs:/app/logs  # 日志目录映射
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 